# Generated by Django 3.0.7 on 2020-08-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarm', '0007_remove_post_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
